# generated by {burglr}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# cli_yesno (copied from cliExtras:::cli_yesno)
# from cliExtras 0.1.0
`cli_yesno` <- function(message, yes = c(
                          "Yes", "Definitely", "For sure", "Yup",
                          "Yeah", "I agree", "Absolutely"
                        ), no = c(
                          "No way", "Not now",
                          "Negative", "No", "Nope", "Absolutely not"
                        ), n_yes = 1, n_no = 1,
                        call = .envir, .envir = parent.frame()) {
  cli_abort_ifnot(c(
    "User input required, but session is not interactive.",
    "Query: ", message
  ), call = .envir, condition = is_interactive())
  qs <- c(sample(yes, n_yes), sample(no, n_no))
  rand <- sample(length(qs))
  cli_inform(message, .envir = .envir)
  utils::menu(qs[rand]) == which(rand == 1)
}

# from cliExtras 0.1.0
`cli_abort_ifnot` <- function(..., condition = FALSE, .data = NULL, call = .envir,
                              .envir = parent.frame()) {
  if (!rlang::is_logical(condition)) {
    condition <- condition_as_fn(condition, .data, call = call)
  }
  if (!condition) {
    cli_abort(..., call = call, .envir = .envir)
  }
  invisible(NULL)
}

# from cliExtras 0.1.0
`condition_as_fn` <- function(condition, .data = NULL, call = parent.frame()) {
  if (!rlang::is_function(condition)) {
    condition <- rlang::as_function(condition)
  }
  condition <- condition(.data)
  if (rlang::is_logical(condition)) {
    return(condition)
  }
  cli_abort("{.fn condition} returned a {.cls {class(condition)} object, not logical.",
    call = call
  )
}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# cli_warn_ifnot (copied from cliExtras:::cli_warn_ifnot)
# from cliExtras 0.1.0
`cli_warn_ifnot` <- function(..., condition = FALSE, .data = NULL, .envir = parent.frame()) {
  if (!rlang::is_logical(condition)) {
    condition <- condition_as_fn(condition, .data, call = call)
  }
  if (!condition) {
    cli_warn(..., .envir = .envir)
  }
  invisible(NULL)
}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# cli_ask (copied from cliExtras:::cli_ask)
# from cliExtras 0.1.0
`cli_ask` <- function(message, ..., prompt = ">> ", .envir = parent.frame()) {
  cli_inform(c(`>` = message, ...), .envir = .envir)
  readline(prompt = prompt)
}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# cli_ul_items (copied from cliExtras:::cli_ul_items)
# from cliExtras 0.1.0
`cli_ul_items` <- function(items) {
  items <- sapply(items, as.character)
  cli::cli_ul()
  sapply(seq_along(items), function(x) {
    cli::cli_li("{.code {names(items)[[x]]}}: {.val {items[[x]]}}")
  })
  cli::cli_end()
}
